### ISSUE TITLE
New task: Fix websites URLs

### ISSUE THREAD

**Issue by rugk** [ENT8R/osm-microtasks#10]
To prepend them with http or https, depending on what is needed…

At least iD complains, if the URL does not have this format. (the input field is red)

**Comment by ENT8R** [comment]
As this tool heavily relies on Overpass, do you maybe have a query which could be used for that?

**Comment by rugk** [comment]
Yep, something like this: https://overpass-turbo.eu/s/EZ3

(includes three website(URL tags)

**Comment by rbovard** [comment]
Thank you for adding this task but why you don't use other keys documented here [1] and here [2] as well (two of them also mentionned by @rugk)?

* `contact:website`
* `url`
* `website:mobile`

[1] https://wiki.openstreetmap.org/wiki/Key:contact
[2] https://wiki.openstreetmap.org/wiki/Key:website

**Comment by ENT8R** [comment]
The same reason why I made the new fax number task a separate task besides the phone number task: https://github.com/ENT8R/osm-microtasks/commit/65d4383600ac4ccb88f5a96d44b45f5f5d748ea4#commitcomment-31860875
I don't want the user to guess which tag he has to edit when using the map mode...
I will think about it. Maybe I will have to do a little UI change...

**Comment by rugk** [comment]
However, that may get irrelevant/solved, when https://github.com/ENT8R/osm-microtasks/issues/12 is done. :smile: As apps can much better reliably remember/decide what field they were editing than human users, so IMHO it is not really useful to double-check it like this. Machines are better here. (If you want to be sure, try introducing some unit tests or so…)

Humans could only have a look at the other tags to see whether it makes sense to edit it, but I doubt this is really needed for these tasks we have here. Our task are pretty atomic and just edit a single element, so they are pretty unrelated to the other tags, i.e. we may safely ignore that. IMHO…
