### ISSUE TITLE
Website quest: enhance "offline" detection

### ISSUE THREAD

**Issue by rugk** [ENT8R/osm-microtasks#17]
The website quest mode, shows:
> There are a lot of wrong URLs in the OSM database. This task finds some of them, checks if it does exist and returns a valid URL.

My interpretation of that is, that it also automatically tries to query that website and checks if that exists. I see some problems with that:
1. Is not it often not accessible due to the Same-Origin constraints of the browser? (i.e. they don't have CORS set…)
2. Checking whether a website is really offline/online or so is harder than you may think, e.g. what status codes do you accept as "exists"? (404?, 500?, …)
  See also https://en.wikipedia.org/wiki/User:InternetArchiveBot for a bot does that on scale in the Wikipedia. You can likely take some ideas of it's doc/implementation…
3. Do/May you actually suggest to the user of this app, to delete the URl, if it is not accessible? (Note that due to 2. you may point the user to try that by themselves…)

**Comment by ENT8R** [comment]
You were right, no website could be checked because of the CORS header. I wrote a simple PHP script which checks whether a website offers the site over HTTPS and in case that this returns a 404 than the script checks if there is a HTTP version of the site and if that does not exist too, the user has to fix it by hand.
And the user also has to fix it by hand if there was another status code than 200.

**Comment by rugk** [comment]
Ah okay, sounds good. Also the expert mode does not allow the user to automatically remove an entry, that is good to prevent false-positives…

Just remember that your PHP script likely is an [open proxy](https://www.acunetix.com/vulnerabilities/web/open-proxy-server/), so users could use it to request arbitrarily sites with your (server) IP. That can be misused, you know…

**Comment by ENT8R** [comment]
Well, it is not a real proxy... The the script just makes several requests to the specified URL and then returns the status code and the (redirected and correct) URL. So no content of the actual page is transferred.
