### ISSUE TITLE
josm support

### ISSUE THREAD

**Issue by bjoernma** [ENT8R/osm-microtasks#2]
Support JOSM as editor, not only online iD, maybe provide "download selection" to import in JOSM?

**Comment by ENT8R** [comment]
Can't you simply select JOSM as your standard editor in the settings of your OSM account? Which editor did you select there? This way **you** would have to change it in your settings and I would not have to add new code or change something...

**Comment by ENT8R** [comment]
I just tested it with JOSM: you have to set JOSM as your default editor in your OSM settings and then you should be able to open the location with JOSM
