### ISSUE TITLE
Don't do duplicate work

### ISSUE THREAD

**Issue by rugk** [ENT8R/osm-microtasks#3]
Did you go through the list [of all other QA tools](https://wiki.openstreetmap.org/wiki/Quality_assurance)? And is there really no one, which you can expand/create PRs there, if you see missing problems. Without having used the others much, I think Maproulette may be very similar e.g.

I mean this project is really nice, but there are so many QA tools already, so you need to explain to users/mappers why we need [yet another "standard"](https://xkcd.com/927/).
Maybe document the "advantages"/differences/goals of your project in the Readme.

**Comment by ENT8R** [comment]
The main reason why I created this tool is that I could not find a project which proposes possible answers to the user so that he can make edits faster... You are right. I will add this to the README.

**Comment by rugk** [comment]
On the other hand the phone number edit is pretty obvious stable code (if there are only numbers), so such things can be done by automated edits. I know the OSM people do not like that…, but is it even disallowed for such a simple thing?

**Comment by ENT8R** [comment]
Mmhh... Take a look at this forum entry: https://forum.openstreetmap.org/viewtopic.php?id=60703 It wasn't even an automated edit...

**Comment by rugk** [comment]
Ah… okay, so the phone number can also be misinterpreted if the source data is bad, fair though… So it really needs some checking. 😄
