### ISSUE TITLE
OAUTH/direct edit in OSM

### ISSUE THREAD

**Issue by rugk** [ENT8R/osm-microtasks#5]
Of course this is a bigger feature, so this is not very important, but at least an idea: What about adding OAUTH and direct edit to the tool?
So you do not have to open iD or so (so it would also solve #4) and can just have a big popup where you see the two numbers in `<code>` (i.e. fixed font width) style directly below each other. I think that makes it easy gto spot errors.
And then just have a button to edit the suggestion and a "change" and "cancel"/close button.

**Comment by ENT8R** [comment]
I created an expert mode which does this... (Can be found here: https://ent8r.github.io/osm-microtasks/tasks/phone/expert/expert.html) But it doesn't work at all...

**Comment by rugk** [comment]
> But it doesn't work at all...

Okay… 🤣
