### ISSUE TITLE
[Blueprint] enhance Company data

### ISSUE THREAD

**Issue by Mannshoch** [ENT8R/osm-microtasks#6]
If I'm on my way with StreetComplete I mostly get asked about opening hours and Building Data.
Why not create a Website where People could Insert their Workplace/Company for themselves, without the need to learn OSM or install an App.

See Mockup:
![company_website](https://user-images.githubusercontent.com/7795891/40906440-0e83bc6a-67e1-11e8-8260-abd1918fb360.png)

**Comment by ENT8R** [comment]
Basically a good idea, but I think this won't work as there is no way to check the quality of the added data.
One possibility would be to connect the website to an OSM account, but then the users need to learn OSM at least a little bit.
I also think that there is already a website for exactly that purpose called https://onosm.org/ (https://wiki.openstreetmap.org/wiki/Onosm.org). It does nearly exactly what you propose and it does not add the data directly to the map but instead posts the data as an anonymous note. Currently there are around 1500 notes full of information and from time to time I am solving some of them (https://ent8r.github.io/NotesReview/expert/?query=onosm.org&limit=1700)

**Comment by Mannshoch** [comment]
👍 Nice to see that something like I wished already exist.

**Comment by ENT8R** [comment]
I'm closing this as this is kind of out of scope for this project as there are others which focus much more on it:
https://osmybiz.osm.ch
https://www.onosm.org/
Nevertheless, thank you for your time you spent creating the mockup and creating the issue...

**Comment by Mannshoch** [comment]
https://osmybiz.osm.ch seems that what I thought it should look like.

Thanks !
